### ISSUE TITLE
go.fd.io/govpp/extras cannot be imported

### ISSUE THREAD

**Issue by yoursunny** [FDio/govpp#111]
`extras` directory is declared as its own module:
https://github.com/FDio/govpp/blob/2155ba39d4353b5d5e36473edfb2268be7b5d9c8/extras/go.mod#L1

However, the HTTP server at `go.fd.io/govpp/extras` is not returning the necessary `<meta name="go-import">` tag, so that the module cannot be imported.

```shell
$ go get go.fd.io/govpp/extras@latest
go: module go.fd.io/govpp@latest found (v0.7.0), but does not contain package go.fd.io/govpp/extras
```

---

### ⚠️ Please, read the following comment with update:  ➡️ https://github.com/FDio/govpp/issues/111#issuecomment-1487424368

**Comment by edwarnicke** [comment]
Could you provide the document that needs to be pushed up?

**Comment by ondrej-fabry** [comment]
Could you share link to the location of source code for the site? I will open PR.

**Comment by edwarnicke** [comment]
So far I've just been pushing up the raw file (since its sufficiently simple):

```
curl https://go.fd.io/govpp
```

```
<html><head>
    <meta name="go-import" content="go.fd.io/govpp git https://github.com/FDio/govpp">
    <meta name="go-source" content="go.fd.io/govpp     https://github.com/FDio/govpp https://github.com/FDio/govpp/tree/master{/dir} https://github.com/FDio/govpp/blob/master{/dir}/{file}#L{line}">
    <meta http-equiv="refresh" content="0; url=https://pkg.go.dev/go.fd.io/govpp" />
</head></html>  
```

**Comment by edwarnicke** [comment]
If we are going to move to having more of a site, it may make sense to build more infra around it.

**Comment by ondrej-fabry** [comment]
> So far I've just been pushing up the raw file (since its sufficiently simple):

Right, understandable. I guess it should not be that much work to use `go` branch in the FD.io site repo to improve maintainability and allow collaboration. For Ligato we just based of master branch and added redirects with static HTML files for each Go module. See https://github.com/ligato/site/blob/go/static/_redirects

**Comment by sknat** [comment]
@edwarnicke do you know where this is hosted ? 
We can probably push a patch, as this seems hugo-based.

**Comment by edwarnicke** [comment]
@sknat Apologies... should have updated here as well :)  Glad all is well.

**Comment by ondrej-fabry** [comment]
### ⚠️ Important Update

so... I think I might have accidentally messed up the extras module info cached in the public Go Proxy. This is because at first I have entered incorrect values for the HTML meta tags in the `go.fd.io/govpp/extras` and when I was testing it, it filled the Go Proxy with invalid info about the module. 😟 

I believe the problem is that Go Proxy now returns the info for **main GoVPP module** instead of **extras submodule**, see here:

```sh
# listing versions WITH Go Proxy
➤ go list -json -m -versions go.fd.io/govpp/extras
{
	"Path": "go.fd.io/govpp/extras",
	"Versions": [
		"v0.6.0-alpha",
		"v0.6.0",
		"v0.7.0",
		"v0.8.0-alpha"
	]
}

# listing versions WITHOUT Go Proxy
➤ GOPROXY=direct go list -json -m -versions go.fd.io/govpp/extras
{
	"Path": "go.fd.io/govpp/extras",
	"Versions": [
		"v0.1.0"
	],
	"Origin": {
		"VCS": "git",
		"URL": "https://github.com/FDio/govpp",
		"Subdir": "extras",
		"TagPrefix": "extras/",
		"TagSum": "t1:x7xgAj5aeOC+DZu5HLiZUY3DgMQA9RRScS5l/36Vcls="
	}
}
```

I have pushed the tag `extras/v0.1.0` to publish _stable_ version of the extras module and without Go Proxy the `latest` gets picked up correctly:


```sh
# downloading latest version WITHOUT Go Proxy
➤ GOPROXY=direct go mod download -json go.fd.io/govpp/extras@latest
{
	"Path": "go.fd.io/govpp/extras",
	"Version": "v0.1.0",
	"Query": "latest",
	"Info": "/home/ondrej/go/pkg/mod/cache/download/go.fd.io/govpp/extras/@v/v0.1.0.info",
	"GoMod": "/home/ondrej/go/pkg/mod/cache/download/go.fd.io/govpp/extras/@v/v0.1.0.mod",
	"Zip": "/home/ondrej/go/pkg/mod/cache/download/go.fd.io/govpp/extras/@v/v0.1.0.zip",
	"Dir": "/home/ondrej/go/pkg/mod/go.fd.io/govpp/extras@v0.1.0",
	"Sum": "h1:vY9nWLGGHD8VoEaL47sP8sQTNBWNE0mN0aERixEUzBE=",
	"GoModSum": "h1:s2FPOGIWR+p3ItFhlC2Zgbw1U5HwZxNYLffeK8Ld/kE=",
	"Origin": {
		"VCS": "git",
		"URL": "https://github.com/FDio/govpp",
		"Subdir": "extras",
		"TagPrefix": "extras/",
		"TagSum": "t1:x7xgAj5aeOC+DZu5HLiZUY3DgMQA9RRScS5l/36Vcls=",
		"Ref": "refs/tags/extras/v0.1.0",
		"Hash": "8b655acb0cc10b9f64247118295c366023980a4d"
	}
}
```

However with the Go Proxy it returns the same response (for govpp main module v0.7.0) as I posted in previous post.

I am afraid this means that users will most likely run into issues when adding the dependency to their Go apps:

```sh
# get latest version WITH Go Proxy
➤ go get go.fd.io/govpp/extras@latest
go: go.fd.io/govpp/extras@v0.7.0: parsing go.mod:
	module declares its path as: go.fd.io/govpp
	        but was required as: go.fd.io/govpp/extras

#  get latest version WITHOUT Go Proxy
➤ GOPROXY=direct go get go.fd.io/govpp/extras@latest
go: added go.fd.io/govpp/extras v0.1.0
```

Specifying the version does not help either:

```sh
# specifying v0.1.0
➤ go get go.fd.io/govpp/extras@v0.1.0
go: downloading go.fd.io/govpp v0.1.0
go: warning: go.fd.io/govpp/extras@v0.1.0: retracted by module author: Versions v0.5.0 and older use old module path git.fd.io/govpp.git
go: to switch to the latest unretracted version, run:
	go get go.fd.io/govpp/extras@latest
```

### 🩹 Available Workaround

So, please use `GOPROXY=direct` when adding the dependency. 

There is one more thing I want to try, that is publishing version that is > v0.7.0 which might force Go Proxy to consider it newer than any version from GoVPP and it might fix the incorrect module info..

**Comment by ondrej-fabry** [comment]
> Setting the version does retrieve the module, but there's a retracted warning.

But, only govpp main module has retracted version. The extras does not. I believe this is precisely because of the invalid cached info in the GoProxy I described above. 

Please try running:

```sh
GOPROXY=direct go get go.fd.io/govpp/extras@v0.1.0
```
