### ISSUE TITLE
Request for a tag

### ISSUE THREAD

**Issue by denis-tingaikin** [FDio/govpp#176]
Hello, govpp folks!

We're interested in tagging the main branch with the fix: https://github.com/FDio/govpp/pull/172

Could you please provide an ETA for the next release that will include the fix?

Thanks!

**Comment by dwallacelf** [comment]
Release 0.9.0 resolves this issue:

https://github.com/FDio/govpp/commit/8debdf0ea14b3ff9cf3877bf41f71694f76a04b0
