### ISSUE TITLE
Using Log2RingSize custom set to more than 10 causes crash in packet writer  for gomemif

### ISSUE THREAD

**Issue by NAYANSEN90** [FDio/govpp#177]
When we are using custom memory config in gomemif, with Log2RingSize set to more than 10, the packet writer after writing some packets panics with index out of range error:

**panic: runtime error: index out of range [770] with length 1**

The packet buffersize doesn't matter. I have tried 2048 to 9128. It doesn't affect the outcome, only the Log2RingSize. I have set it to 11, 12 it panics.

I see that the default Log2RingSize is set to 10.

**Comment by dwallacelf** [comment]
Can you please provide specific references to the code that has been modified and also provide a recipe to reproduce the issue?
