### ISSUE TITLE
Would you please add an example  using mulit rx and tx queue to extras/gomemif/examples 

### ISSUE THREAD

**Issue by eiguleo** [FDio/govpp#196]
i have tried add NumQueuePairs=2 to memif.Arguments and i.GetRxQueue(1) in Responder function in file  extras/gomemif/examples/icmp_reponder_cb/icmp_reponder_cb.go, but does not work at all

thank you

**Comment by sknat** [comment]
@eiguleo Thanks for reporting this, agreed this part of the repository is not very well documented, we'll try to address it
