### ISSUE TITLE
Run more steps in CI 

### ISSUE THREAD

**Issue by ondrej-fabry** [FDio/govpp#49]
To improve the quality of the code that is merged to master, the CI pipeline should perform more tests or checks for common things developers forget to update.

- [x] ~~verify contents of `go.mod` file are up-to-date and `go.sum` is not missing any entry~~
  - #61 
- [x] ~~add [golangci-lint](https://golangci-lint.run/usage/install#github-actions) for linting and code checks~~
  - #69 
- [x] ~~add base for integration/e2e tests against real VPP instances~~
  - #75 
- [x] run examples against master version of VPP and 2-3 recent VPP releases

**Comment by dwallacelf** [comment]
Do we need a docs verification task?

I was able to review PR#70 by going to the 'Files Changed' tab and selecting '...'/'View file' for docs/troubleshooting.md which showed that the markdown rendered correctly.

However, if the syntax was incorrect, does anything in the CI run *.md files through the github renderer and mark it as not mergeable?

As an optimization, it would be good to skip the build verification tasks for docs only PR's, but may not be worth implementing if it make the CI too complex.

**Comment by ondrej-fabry** [comment]
All tasks complete as part of release v0.7.0. For the rest separate issues were created for tracking them.
