### ISSUE TITLE
Create Troubleshooting Guide document

### ISSUE THREAD

**Issue by ondrej-fabry** [FDio/govpp#60]
Create a Troubleshooting guide docs with common problems that users often run into.

- info about how to increase log verbosity and enable debugging of various GoVPP components
- send/receive error  `unknown message: ...` - occurs when running VPP version with incompatible messages
- connection errors - possibly missing socket? perhaps incorrect path or wrong VPP config?
- _add more.._

**Comment by VladoLavor** [comment]
A few more notes:
* explain how to deal with deprecated messages and how the API message versioning works
* how to use stats interfaces `StatsAPI` vs `StatsProvider`
* how to troubleshoot VPP not replying to some message
* what to do if govpp tries to connect before the VPP socket is ready

**Comment by ondrej-fabry** [comment]
>     * how to use stats interfaces `StatsAPI` vs `StatsProvider`
> 

This one does not seem to be in "_trouble_".. :) It seems more suitable for some _User Guide_ document. Let me create a separate issue for that. It would be definitely useful to have as well.
