### ISSUE TITLE
Question： missing binary API reply with sequence number

### ISSUE THREAD

**Issue by fatelei** [FDio/govpp#78]
vpp is a single thread server, so it handles request one by one, and response it one by one. i don't know how the disorder will be happen.

**Comment by ondrej-fabry** [comment]
To be honest, I am not really sure what you are asking here. The request and replies are matched by the _context_ field in the message itself. Each _Channel_ or _Stream_ has unique context number which is used in the request and VPP replies using the same context, that is how GoVPP client matches request/reply even if they are processed out of order.

**Comment by fatelei** [comment]
i using govpp, i found this error `missing binary API reply with sequence number`. Because of vpp is single thread server, it handle the request one by one, so i think the vpp will echo the request number in order. I want to known what kind of situation will lead this error.

**Comment by fatelei** [comment]
close it, i will check vpp is single thread or multi thread. i

**Comment by ondrej-fabry** [comment]
Could you share the code you are using to send/receive requests?

**Comment by ondrej-fabry** [comment]
This error message occurs when you receive a reply that has higher sequence number than expected. The sequence number is actually part of the context field mentioned above and each Channel contains it's own sequence number which is increased every time you send request. The RequestContext you get from SendRequest will be used to check the sequence number in the reply you get to verify it matches. However if you use the Channel in multiple goroutines or if you send multiple requests silmutaneously before receiving reply from the previous request you will run into this error.
