### ISSUE TITLE
ubuntu 22.04 apt update issue after adding the repo

### ISSUE THREAD

**Issue by ultperf** [FDio/govpp#92]
followed here but doesnt work on ubuntu 22.04

https://fd.io/gettingstarted/installing/

```
W: https://packagecloud.io/fdio/release/ubuntu/dists/bionic/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://packagecloud.io/fdio/master/ubuntu/dists/bionic/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```

**Comment by ondrej-fabry** [comment]
Hello @ultperf, how is this issue related to GoVPP project? What were you trying to do and what did not work in expected way? What command did you execute?

---

> followed here but doesnt work on ubuntu 22.04
> 
> [fd.io/gettingstarted/installing](https://fd.io/gettingstarted/installing/)

That link with VPP installation guide is for **Ubuntu 18.04 (bionic)**, NOT for **Ubuntu 22.04 (jammy)**.

To install VPP in newer releases of Ubuntu, you can use this quick install script:

```
# Script with automatic resolving of OS
curl -s https://packagecloud.io/install/repositories/fdio/2210/script.deb.sh | sudo bash
```

> source: https://packagecloud.io/fdio/2210/install#bash-deb
